### ISSUE TITLE
Exception stopping consumer: Exception (504) Reason: "channel/connection is not open"

### ISSUE THREAD

**Issue by NikitaZhdanov** [matrixbotio/rmqworker-lib#56]
каждые ~полчаса ошибка

    Exception stopping consumer: Exception (504) Reason: "channel/connection is not open"
code:
    -32,603
stack:
    at /go/pkg/mod/github.com/matrixbotio/rmqworker-lib@v1.22.10/workers.go:223 at /go/pkg/mod/github.com/matrixbotio/rmqworker-lib@v1.22.10/workers.go:367 at /go/pkg/mod/github.com/sagleft/simple-cron@v1.3.0/cron.go:73

Это там где завершение подписки я добавил

Можно попробовать read lock туда впендюрить

**Comment by Sagleft** [comment]
🤔 еще актуально?

**Comment by Sagleft** [comment]
в core у меня такой ошибки нет, похоже

**Comment by NikitaZhdanov** [comment]
хм, да, RLock я, оказывается, уже туда добавлял, значит проблема если и есть, то не в этом, пока закроем, если повторится - переоткроем и будем копать
